version: '3.1'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: robotdb
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data